stages:
  - build
  - deploy
 

# Build Stage: Build the Docker image
build:
  stage: build
  script:
    - echo "Building the Docker image."
    - docker build -t nginx:v2.0 .  # Build the Docker image locally with the tag 'my-local-image'
  only:
    - main  # Or any branch you want to trigger the build on
  tags:
    - runner  

# Deploy Stage: Deploy the Docker image locally
deploy:
  stage: deploy
  script:
    - echo "Deploying the Docker container locally"
    # Run the new container locally
    - docker container stop nginx-cicd
    - docker container rm nginx-cicd
    - docker run -d -p 8080:80 --name nginx-cicd nginx:v2.0
  only:
    - main  # Only deploy from the master branch (adjust as needed)
  tags:
    - runner  

